### ISSUE TITLE
DatabaseDescriptor gives NullPointerException

### ISSUE THREAD

**Issue by muriumiqbal** [yukim/cassandra-bulkload-example#2]
Using the provided BulkLoad.java, as is, to create the SSTables gives the following error:

> Exception in thread "main" java.lang.ExceptionInInitializerError
>   at org.apache.cassandra.cql3.statements.UpdateStatement.addUpdateForKey(UpdateStatement.java:109)
>   at org.apache.cassandra.io.sstable.CQLSSTableWriter.rawAddRow(CQLSSTableWriter.java:218)
>   at org.apache.cassandra.io.sstable.CQLSSTableWriter.addRow(CQLSSTableWriter.java:138)
>   at org.apache.cassandra.io.sstable.CQLSSTableWriter.addRow(CQLSSTableWriter.java:113)
>   at bulkload.BulkLoad.main(BulkLoad.java:145)
> Caused by: java.lang.NullPointerException
>   at org.apache.cassandra.config.DatabaseDescriptor.createAllDirectories(DatabaseDescriptor.java:605)
>   at org.apache.cassandra.db.Keyspace.<clinit>(Keyspace.java:73)

Using the provided gradle-wrapper.jar file works fine, though. 

Is there something necessary which is present in the project that isn't in the provided source file? Or, some additional configuration that needs to be set, but is not mentioned in the associated blog post?

**Comment by yukim** [comment]
We had bug in  recent version of Cassandra (both 2.0 and 2.1) and was fixed in [CASSANDRA-8808](https://issues.apache.org/jira/browse/CASSANDRA-8808) to be released in v2.0.14 and 2.1.4.

**Comment by muriumiqbal** [comment]
Alright. Thank you!
