### ISSUE TITLE
IndexOutOFBoundException while running sstableloader

### ISSUE THREAD

**Issue by mj-jadhav** [yukim/cassandra-bulkload-example#8]
cassandra version: 2.1.8
cqlsh version: 5.0.1
CQL spec version: 3.2.1
Scylladb version: 1.6.0
Got following error:
`java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:538)
        at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:410)
        at org.apache.cassandra.utils.ByteBufferUtil.toLong(ByteBufferUtil.java:377)
        at org.apache.cassandra.serializers.TimestampSerializer.deserialize(TimestampSerializer.java:78)
        at org.apache.cassandra.serializers.TimestampSerializer.deserialize(TimestampSerializer.java:30)
        at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68)
        at com.scylladb.tools.SSTableToCQL$RowBuilder.addWhere(SSTableToCQL.java:239)
        at com.scylladb.tools.SSTableToCQL$RowBuilder.updateColumn(SSTableToCQL.java:537)
        at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:456)
        at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:484)
        at com.scylladb.tools.SSTableToCQL$RowBuilder.access$400(SSTableToCQL.java:108)
        at com.scylladb.tools.SSTableToCQL.process(SSTableToCQL.java:660)
        at com.scylladb.tools.SSTableToCQL.stream(SSTableToCQL.java:693)
        at com.scylladb.tools.BulkLoader.main(BulkLoader.java:586)`

**Comment by yukim** [comment]
Looks like exception is from ScyllaDB, please report them instead.
